In [2]:
# General libraries
import os
import numpy as np
import pandas as pd 
import random
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

# Deep learning libraries
import keras.backend as K
from keras.models import Model, Sequential
from keras.layers import Input, Dense, Flatten, Dropout, BatchNormalization
from keras.layers import Conv2D, SeparableConv2D, MaxPool2D, LeakyReLU, Activation
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
import tensorflow as tf

# Setting seeds for reproducibility
seed = 232
np.random.seed(seed)
tf.random.set_seed(seed)

Using TensorFlow backend.


In [3]:
#reading the data
df=pd.read_csv("Data_Entry_2017.csv") 

ASK...I didnt like this method...of moving files...any other way?
ASK....checked with "file size" that all is moved..any other way to check?

In [ ]:
#collecting all images in one folder
import shutil, os
src='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images1/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src)
for f in files:
    shutil.copyfile(src+f,dst+f)

In [ ]:
#collecting all images in one folder
src1='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images2/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src1)
for f in files:
    shutil.copyfile(src1+f,dst+f)

In [ ]:
#collecting all images in one folder
src2='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images3/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src2)
for f in files:
    shutil.copyfile(src2+f,dst+f)

In [ ]:
#collecting all images in one folder
src3='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images4/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src3)
for f in files:
    shutil.copyfile(src3+f,dst+f)

In [ ]:
#collecting all images in one folder
src4='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images5/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src4)
for f in files:
    shutil.copyfile(src4+f,dst+f)

In [ ]:
#collecting all images in one folder
src5='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images6/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src5)
for f in files:
    shutil.copyfile(src5+f,dst+f)

In [ ]:
#collecting all images in one folder
src6='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images7/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src6)
for f in files:
    shutil.copyfile(src6+f,dst+f)

In [ ]:
#collecting all images in one folder
src7='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images8/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src7)
for f in files:
    shutil.copyfile(src7+f,dst+f)

In [ ]:
#collecting all images in one folder
src8='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images9/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src8)
for f in files:
    shutil.copyfile(src8+f,dst+f)

In [ ]:
#collecting all images in one folder
src9='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images10/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src9)
for f in files:
    shutil.copyfile(src9+f,dst+f)

In [ ]:
src10='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images11/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src10)
for f in files:
    shutil.copyfile(src10+f,dst+f)

In [ ]:
#collecting all images in one folder
src11='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/images12/'
dst='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'

files = os.listdir(src11)
for f in files:
    shutil.copyfile(src11+f,dst+f)

In [4]:
#convert the files in train_val_list.txt to a python list 

train_val_list= open('/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/train_val_list.txt').read().split()



In [11]:
print(train_val_list[0:5])

['00000001_000.png', '00000001_001.png', '00000001_002.png', '00000002_000.png', '00000004_000.png']


In [12]:
print(len(train_val_list))

86524


In [13]:
#moving images marked as trained from img_all to train_img folder
# will be applying the Deep Learning librries on these images
import shutil, os
source='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/img_all/'
destination='/Users/neeharikasinha/Documents/datascience-course/Chestxray-cardiomegaly/train_img/'

files = train_val_list
for f in files:
    shutil.copyfile(source+f,destination+f)

In [14]:
#renaming the columns names
df.rename(columns={'Image Index':'img_index','Finding Labels':'labels','Follow-up #':'follow_up','Patient ID':'pa_id',
                   'Patient Age':'pa_age','Patient Gender':'pa_gender','View Position':'view_position'}, inplace=True)

In [19]:
df.columns

Index(['img_index', 'labels', 'follow_up', 'pa_id', 'pa_age', 'pa_gender',
       'view_position', 'OriginalImage[Width', 'Height]',
       'OriginalImagePixelSpacing[x', 'y]'],
      dtype='object')

In [20]:
#Selecting the images under train_val_list from Data_Entry_2017.csv file

df_train_img = df[df.img_index.isin(train_val_list)]

In [21]:
df_train_img.head()

img_index                  labels  follow_up  pa_id  pa_age  \
0   00000001_000.png            Cardiomegaly          0      1      58   
1   00000001_001.png  Cardiomegaly|Emphysema          1      1      58   
2   00000001_002.png   Cardiomegaly|Effusion          2      1      58   
3   00000002_000.png              No Finding          0      2      81   
12  00000004_000.png             Mass|Nodule          0      4      82   

   pa_gender view_position  OriginalImage[Width  Height]  \
0          M            PA                 2682     2749   
1          M            PA                 2894     2729   
2          M            PA                 2500     2048   
3          M            PA                 2500     2048   
12         M            AP                 2500     2048   

    OriginalImagePixelSpacing[x     y]  
0                         0.143  0.143  
1                         0.143  0.143  
2                         0.168  0.168  
3                         0.171  0.171  
12                        0.168  0.168

In [22]:
len(df_train_img)

86524

In [28]:
#checking images with variouslabels
print(df_train_img['labels'].unique())

['Cardiomegaly' 'Cardiomegaly|Emphysema' 'Cardiomegaly|Effusion'
 'No Finding' 'Mass|Nodule' 'Infiltration' 'Effusion|Infiltration'
 'Nodule' 'Emphysema' 'Effusion' 'Atelectasis' 'Effusion|Mass'
 'Effusion|Infiltration|Nodule' 'Atelectasis|Effusion|Pleural_Thickening'
 'Pleural_Thickening' 'Fibrosis|Infiltration'
 'Fibrosis|Infiltration|Pleural_Thickening' 'Fibrosis'
 'Infiltration|Mass|Nodule' 'Atelectasis|Cardiomegaly|Fibrosis'
 'Atelectasis|Infiltration' 'Consolidation|Mass'
 'Consolidation|Effusion|Infiltration' 'Infiltration|Pleural_Thickening'
 'Atelectasis|Effusion' 'Fibrosis|Infiltration|Nodule' 'Nodule|Pneumonia'
 'Infiltration|Nodule' 'Mass' 'Effusion|Pleural_Thickening'
 'Edema|Effusion|Infiltration|Pleural_Thickening|Pneumonia'
 'Effusion|Fibrosis' 'Pneumonia' 'Edema|Effusion|Infiltration'
 'Edema|Effusion' 'Consolidation|Effusion|Infiltration|Mass'
 'Consolidation|Effusion|Infiltration|Nodule' 'Pneumothorax'
 'Atelectasis|Effusion|Infiltration' 'Effusion|Emphysema|Infiltra

In [29]:
#assigning "1" to images which has atleast "Cardiomegaly"
df_train_img['Cardiomegaly'] = np.where(df_train_img.loc[:,'labels'].str.contains('Cardiomegaly'),1,0)
print(df.head())

          img_index                  labels  follow_up  pa_id  pa_age  \
0  00000001_000.png            Cardiomegaly          0      1      58   
1  00000001_001.png  Cardiomegaly|Emphysema          1      1      58   
2  00000001_002.png   Cardiomegaly|Effusion          2      1      58   
3  00000002_000.png              No Finding          0      2      81   
4  00000003_000.png                  Hernia          0      3      81   

  pa_gender view_position  OriginalImage[Width  Height]  \
0         M            PA                 2682     2749   
1         M            PA                 2894     2729   
2         M            PA                 2500     2048   
3         M            PA                 2500     2048   
4         F            PA                 2582     2991   

   OriginalImagePixelSpacing[x     y]  Cardiomegaly  No Finding  
0                        0.143  0.143             1           0  
1                        0.143  0.143             1           0  
2       

/Users/neeharikasinha/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [30]:
#signing "2" to images which are "No Findings"and is Normal
df_train_img['No Finding'] = np.where(df_train_img.loc[:,'labels'].str.contains('No Finding'),2,0)
print(df.head())


          img_index                  labels  follow_up  pa_id  pa_age  \
0  00000001_000.png            Cardiomegaly          0      1      58   
1  00000001_001.png  Cardiomegaly|Emphysema          1      1      58   
2  00000001_002.png   Cardiomegaly|Effusion          2      1      58   
3  00000002_000.png              No Finding          0      2      81   
4  00000003_000.png                  Hernia          0      3      81   

  pa_gender view_position  OriginalImage[Width  Height]  \
0         M            PA                 2682     2749   
1         M            PA                 2894     2729   
2         M            PA                 2500     2048   
3         M            PA                 2500     2048   
4         F            PA                 2582     2991   

   OriginalImagePixelSpacing[x     y]  Cardiomegaly  No Finding  
0                        0.143  0.143             1           0  
1                        0.143  0.143             1           0  
2       

/Users/neeharikasinha/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [33]:
#collecting images with "No Findings"
df_Normal = df_train_img[df_train_img['No Finding']==2]

In [34]:
df_Normal.head()

img_index      labels  follow_up  pa_id  pa_age pa_gender  \
3   00000002_000.png  No Finding          0      2      81         M   
13  00000005_000.png  No Finding          0      5      69         F   
14  00000005_001.png  No Finding          1      5      69         F   
15  00000005_002.png  No Finding          2      5      69         F   
16  00000005_003.png  No Finding          3      5      69         F   

   view_position  OriginalImage[Width  Height]  OriginalImagePixelSpacing[x  \
3             PA                 2500     2048                        0.171   
13            PA                 2048     2500                        0.168   
14            AP                 2500     2048                        0.168   
15            AP                 2500     2048                        0.168   
16            PA                 2992     2991                        0.143   

       y]  Cardiomegaly  No Finding  
3   0.171             0           2  
13  0.168             0           2  
14  0.168             0           2  
15  0.168             0           2  
16  0.143             0           2

In [35]:
len(df_Normal)

50500

In [36]:
#collecting images with "Cardiomegaly"
df_Cardiomegaly = df_train_img[df_train_img['Cardiomegaly']==1]

In [37]:
df_Cardiomegaly.head()

img_index                             labels  follow_up  pa_id  \
0    00000001_000.png                       Cardiomegaly          0      1   
1    00000001_001.png             Cardiomegaly|Emphysema          1      1   
2    00000001_002.png              Cardiomegaly|Effusion          2      1   
23   00000008_000.png                       Cardiomegaly          0      8   
175  00000033_000.png  Atelectasis|Cardiomegaly|Fibrosis          0     33   

     pa_age pa_gender view_position  OriginalImage[Width  Height]  \
0        58         M            PA                 2682     2749   
1        58         M            PA                 2894     2729   
2        58         M            PA                 2500     2048   
23       69         F            PA                 2048     2500   
175      72         F            PA                 2992     2745   

     OriginalImagePixelSpacing[x     y]  Cardiomegaly  No Finding  
0                          0.143  0.143             1           0  
1                          0.143  0.143             1           0  
2                          0.168  0.168             1           0  
23                         0.171  0.171             1           0  
175                        0.143  0.143             1           0

In [38]:
len(df_Cardiomegaly)

1707

In [40]:
86524-(50500+1707)

34317

ASk: am I correct?
Notes: In total there are 86524 images selected for training. In which 50500 are No Findings and 1707 are having Cardiomegaly. Since the patient visited several time during the treatment, as seen by patient id , it says that the number of No Findings or Normal images are more than the images having the disease. 